name: Package and Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  package-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip uninstall black -y

    - name: Package application
      run: |
        pyinstaller --clean --noconfirm packaging.spec

    - name: Upload packaged artifact
      uses: actions/upload-artifact@v4
      with:
        name: packaged-app
        path: dist/

    - name: Create or update release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/**
        tag_name: latest
        name: Latest Release
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
